const actionTypes = {
  SESSION_STARTED: "Session started",
  AUTHORING_CHANGED: "Authoring changed",
  LOADED_CHALLENGE_FROM_AUTHORING: "Loaded challenge from authoring",
  NAVIGATED: "Navigated",
  NAVIGATED_HOME: "Navigated home",
  CHALLENGE_COMPLETED: "Challenge completed",
  CHALLENGE_RETRIED: "Challenge retried",
  BRED: "Bred",
  ALLELE_CHANGED: "Allele changed",
  SEX_CHANGED: "Sex changed",
  FERTILIZED: "Fertilized",
  CLUTCH_BRED: "Clutch bred",
  CLUTCH_CLEARED: "Clutch cleared",
  READY_TO_ANSWER: "Ready to answer",
  HATCHED: "Hatched",
  EGG_SUBMITTED: "Egg submitted",
  EGG_ACCEPTED: "Egg accepted",
  EGG_REJECTED: "Egg rejected",
  OFFSPRING_KEPT: "Offspring kept",
  BASKET_SELECTION_CHANGED: "Basket selection changed",
  DRAKE_SELECTION_CHANGED: "Drake selection changed",
  DRAKE_SUBMITTED: "Drake submitted",
  ZOOM_CHALLENGE_WON: "Zoom challenge won",
  NAVIGATED_NEXT_CHALLENGE: "Navigated to next challenge",
  NAVIGATED_PAGE: "Navigated to another page",
  MODAL_DIALOG_SHOWN: "Modal dialog shown",
  MODAL_DIALOG_DISMISSED: "Modal dialog dismissed",
  NOTIFICATIONS_SHOWN: "Notifications shown",
  ADVANCED_TRIAL: "Advanced to next trial",
  TOGGLE_MAP: "Map toggled",
  ENTERED_CHALLENGE_FROM_ROOM: "Entered challenge from room",
  LOAD_SAVED_STATE: "Loaded saved state",
  VIEWED_EASTER_EGG: "Viewed easter egg"
};

export default actionTypes;
